import { FilmStyle } from './types';

export const filmStyles: FilmStyle[] = [
  {
    id: 'none',
    name: 'Clean',
    description: 'No effects applied',
    filter: '',
    grain: 0,
    vignette: 0,
    dustOpacity: 0,
    lightLeakOpacity: 0,
    colorShift: '',
  },
  {
    id: 'kodak-gold',
    name: 'Kodak Gold',
    description: 'Warm highlights, soft blacks',
    filter: 'sepia(12%) saturate(115%) brightness(102%) contrast(95%)',
    grain: 15,
    vignette: 20,
    dustOpacity: 5,
    lightLeakOpacity: 0,
    colorShift: 'hue-rotate(-5deg)',
  },
  {
    id: 'fuji-superia',
    name: 'Fuji Superia',
    description: 'Cool shadows, higher contrast',
    filter: 'saturate(110%) brightness(100%) contrast(108%)',
    grain: 12,
    vignette: 15,
    dustOpacity: 3,
    lightLeakOpacity: 0,
    colorShift: 'hue-rotate(8deg)',
  },
  {
    id: 'portra-400',
    name: 'Portra 400',
    description: 'Natural tones, perfect for portraits',
    filter: 'saturate(95%) brightness(103%) contrast(92%) sepia(5%)',
    grain: 10,
    vignette: 12,
    dustOpacity: 2,
    lightLeakOpacity: 0,
    colorShift: '',
  },
  {
    id: 'ektar-100',
    name: 'Ektar 100',
    description: 'Vivid colors, fine grain',
    filter: 'saturate(130%) brightness(100%) contrast(110%)',
    grain: 5,
    vignette: 10,
    dustOpacity: 2,
    lightLeakOpacity: 0,
    colorShift: '',
  },
  {
    id: 'cinestill-800',
    name: 'CineStill 800T',
    description: 'Cinematic tungsten look',
    filter: 'saturate(105%) brightness(95%) contrast(110%)',
    grain: 20,
    vignette: 25,
    dustOpacity: 5,
    lightLeakOpacity: 8,
    colorShift: 'hue-rotate(-12deg)',
  },
  {
    id: 'expired',
    name: 'Expired Film',
    description: 'Unpredictable color shifts',
    filter: 'sepia(25%) saturate(70%) brightness(92%) contrast(82%)',
    grain: 30,
    vignette: 35,
    dustOpacity: 15,
    lightLeakOpacity: 20,
    colorShift: 'hue-rotate(18deg)',
  },
  {
    id: 'tri-x',
    name: 'Tri-X 400',
    description: 'Classic B&W with rich blacks',
    filter: 'grayscale(100%) contrast(115%) brightness(98%)',
    grain: 18,
    vignette: 20,
    dustOpacity: 8,
    lightLeakOpacity: 0,
    colorShift: '',
  },
  {
    id: 'hp5',
    name: 'HP5 Plus',
    description: 'Softer B&W with more gray tones',
    filter: 'grayscale(100%) contrast(100%) brightness(102%)',
    grain: 15,
    vignette: 15,
    dustOpacity: 5,
    lightLeakOpacity: 0,
    colorShift: '',
  },
];
